name: pnml_adv
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pip:
    - jsonargparse